<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>aspnet-ReservasFodun.Web-c68c31cf-fd16-4ece-8063-447b71e7df79</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.27" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.27" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.27" />

		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.27">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>

		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.27" />

		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.27">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>

		<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.7" />

		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\ReservasFodun.Application\ReservasFodun.Application.csproj" />
		<ProjectReference Include="..\ReservasFodun.Infrastructure\ReservasFodun.Infrastructure.csproj" />
	</ItemGroup>

</Project>